### ISSUE TITLE
项目起不来，按你说的步骤

### ISSUE THREAD

**Issue by abin-jb** [sanyuan0704/react-ssr#1]

**Comment by sanyuan0704** [comment]
有报错的截图吗？麻烦你说一下是什么报错。
退出再重启可以吗？

**Comment by abin-jb** [comment]
就是先npm install,然后npm run dev,之后提示缺了几个依赖，加上之后，也没有提示访问地址，没有你说的3001服务端口啊

**Comment by sanyuan0704** [comment]
那你单独运行一下server目录下的index. js看看，这个是启动服务的，npm run dev其实做了两件事，一件是打包server端和client端的代码，一件是启动服务，前面没报错应该已经打包好了 。


 
---原始邮件---
发件人: "abin"<notifications@github.com>
发送时间: 2019年7月8日(星期一) 下午4:34
收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>;
抄送: "sanyuan0704"<494130947@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1)



就是先npm install,然后npm run dev,之后提示缺了几个依赖，加上之后，也没有提示访问地址，没有你说的3001服务端口啊

**Comment by pcjgithub** [comment]
楼主，你没有上传scripts文件夹，那些npm run dev的命令找不到，肯定跑不起来的
![image](https://user-images.githubusercontent.com/20919164/60856486-e88e8280-a239-11e9-82be-2e46e5183aa6.png)

**Comment by sanyuan0704** [comment]
scripts在package.json里面配置了，通过npm是可以跑这个命令的



------------------ 原始邮件 ------------------
发件人: "pcjgithub"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 中午11:09
收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>; 
抄送: "杨兴元"<494130947@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1)




楼主，你没有上传scripts文件夹，那些npm run dev的命令找不到，肯定跑不起来的

**Comment by pcjgithub** [comment]
![image](https://user-images.githubusercontent.com/20919164/60856717-b0d40a80-a23a-11e9-9730-8ad56a48f296.png)
发的npm的scripts包路径是不是写错了，目前项目是没办法启动的，找不到命令

**Comment by pcjgithub** [comment]
你用的操作系统是什么？我这边是在mac os上运行不了

**Comment by sanyuan0704** [comment]
你先npm install npm-run-all --save试试



------------------ 原始邮件 ------------------
发件人: "pcjgithub"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 中午11:17
收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>; 
抄送: "杨兴元"<494130947@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1)





 发的npm的scripts包路径是不是写错了，目前项目是没办法启动的，找不到命令

**Comment by sanyuan0704** [comment]
我用的win10，请问你也是报npm-run-all命令找不到吗？




------------------ 原始邮件 ------------------
发件人: "pcjgithub"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 中午11:18
收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>; 
抄送: "杨兴元"<494130947@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1)




你用的操作系统是什么？我这边是在mac os上运行不了

**Comment by abin-jb** [comment]
装完依赖的结果，打包成功，但是服务没起



------------------ 原始邮件 ------------------
发件人: "sanyuan0704"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 中午11:18
收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>; 
抄送: "阿斌"<2313517435@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1)



你先npm install npm-run-all --save试试 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "pcjgithub"<notifications@github.com>;  
 发送时间: 2019年7月9日(星期二) 中午11:17 
 收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>;  
 抄送: "杨兴元"<494130947@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1) 
 
 
 
 
 
  发的npm的scripts包路径是不是写错了，目前项目是没办法启动的，找不到命令

**Comment by sanyuan0704** [comment]
你好，能不能把打包的命令行窗口那里截个图

**Comment by sanyuan0704** [comment]
你可以进入src/server目录，然后node index.js单独启动服务试试

**Comment by pcjgithub** [comment]
![image](https://user-images.githubusercontent.com/20919164/60857247-65baf700-a23c-11e9-8cda-adc25b2a0d11.png)

安装完npm-run-all还是不行，不过代码还是比较详细的，看代码就可以了

**Comment by sanyuan0704** [comment]
按照提示，你还需要npm install nodemon --save，这是我的疏忽，我马上在项目说明加上



------------------ 原始邮件 ------------------
发件人: "pcjgithub"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 中午11:24
收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>; 
抄送: "杨兴元"<494130947@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1)





 安装完npm-run-all还是不行，不过代码还是比较详细的，看代码就可以了

**Comment by abin-jb** [comment]
![K3GMDHHF36G2OGWP{0KP7FA](https://user-images.githubusercontent.com/26585446/60857215-49b75580-a23c-11e9-83be-bf7f92f24398.png)
好了吗

**Comment by sanyuan0704** [comment]
项目起码还是需要启动起来，不然后面学起来会没动力




------------------ 原始邮件 ------------------
发件人: "pcjgithub"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 中午11:17
收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>; 
抄送: "杨兴元"<494130947@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1)





 发的npm的scripts包路径是不是写错了，目前项目是没办法启动的，找不到命令

**Comment by sanyuan0704** [comment]
ssr项目启动算成功的，不过你的后端的4000端口没有开启，后端的数据接口你会那不到，在node_server目前按照步骤1执行下

**Comment by sanyuan0704** [comment]
> ![K3GMDHHF36G2OGWP{0KP7FA](https://user-images.githubusercontent.com/26585446/60857215-49b75580-a23c-11e9-83be-bf7f92f24398.png)
> 好了吗

ssr项目启动算成功的，不过你的后端的4000端口没有开启，后端的数据接口你会那不到，在node_server目前按照步骤1执行下

**Comment by pcjgithub** [comment]
已经启动起来了，ths

**Comment by sanyuan0704** [comment]
------------------ 原始邮件 ------------------
发件人: "pcjgithub"<notifications@github.com>; 
发送时间: 2019年7月9日(星期二) 中午11:38
收件人: "sanyuan0704/react-ssr"<react-ssr@noreply.github.com>; 
抄送: "杨兴元"<494130947@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [sanyuan0704/react-ssr] 项目起不来，按你说的步骤 (#1)




已经启动起来了，ths
